global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']

  - job_name: "fastapi"
    static_configs:
      - targets: [ "fastapi:9000" ]